# Exact baseline for pre-existing Dialyzer findings.
#
# Keep entries specific: a changed or resolved warning makes
# `mix dialyzer --list-unused-filters` fail until this file is updated.
[
  {"lib/jido_code/architecture/checker.ex", "The pattern can never match the type Keyword.t()."},
  {"lib/jido_code/architecture/checker.ex",
   "The pattern variable _line@1 can never match the type, because it is covered by previous clauses."},
  {"lib/jido_code/architecture/checker.ex",
   "The pattern variable __location@1 can never match the type, because it is covered by previous clauses."},
  {"lib/jido_code/factory/delegated_result_gate.ex",
   "The pattern variable __invalid@1 can never match the type, because it is covered by previous clauses."},
  {"lib/jido_code/factory/egress_broker.ex",
   "The pattern variable __invalid@1 can never match the type, because it is covered by previous clauses."},
  {"lib/jido_code/factory/evaluation/adjudication.ex",
   "The pattern variable __invalid@1 can never match the type, because it is covered by previous clauses."},
  {"lib/jido_code/factory/extensions/mcp/transport_adapter.ex",
   "Attempt to test for equality with an opaque type %MapSet{:map => MapSet.internal(_)}."},
  {"lib/jido_code/factory/extensions/registry.ex",
   "Attempt to test for equality with an opaque type %MapSet{:map => MapSet.internal(_)}."},
  {"lib/jido_code/factory/model/dispatch.ex",
   "The pattern pattern <__profile@1, __credential@1> can never match the type, because it is covered by previous clauses."},
  {"lib/jido_code/factory/sandbox/isolation_profile.ex",
   "Attempt to test for equality with an opaque type %MapSet{:map => MapSet.internal(_)}."},
  {"lib/jido_code/factory/sandbox/resource_enforcer.ex",
   "Attempt to test for equality with an opaque type %MapSet{:map => MapSet.internal(_)}."},
  {"lib/jido_code/factory/tool/proposal.ex",
   "Attempt to test for equality with an opaque type %MapSet{:map => MapSet.internal(_)}."},
  {"lib/jido_code/integrations/req_repository_provider.ex",
   "The pattern variable __invalid@1 can never match the type, because it is covered by previous clauses."},
  {"lib/jido_code/integrations/req_repository_provider.ex",
   "The pattern can never match the type \n  {:error,\n   %JidoCode.Knowledge.Error{\n     :__exception__ => true,\n     :kind =>\n       :conflict\n       | :corrupt\n       | :incompatible\n       | :invalid_input\n       | :locked\n       | :persistence_failure\n       | :stale_precondition\n       | :timeout\n       | :unauthorized\n       | :unavailable,\n     :message => binary(),\n     :operation => atom(),\n     :retry => :never | :refresh | :retry | :verify_receipt\n   }}\n."},
  {"lib/jido_code/integrations/req_repository_provider.ex",
   "Type mismatch in call without opaque term in member?."},
  {"lib/jido_code/knowledge/backup.ex",
   "The pattern pattern {'error', __reason@1} can never match the type, because it is covered by previous clauses."},
  {"lib/jido_code/knowledge/backup.ex",
   "The pattern pattern {'error', _reason@2} can never match the type, because it is covered by previous clauses."},
  {"lib/jido_code/knowledge/control/eligibility.ex",
   "The pattern variable __invalid@1 can never match the type, because it is covered by previous clauses."},
  {"lib/jido_code/knowledge/control/harness_profile.ex",
   "The pattern variable __invalid@1 can never match the type, because it is covered by previous clauses."},
  {"lib/jido_code/knowledge/control/obligation.ex",
   "The pattern variable __invalid@1 can never match the type, because it is covered by previous clauses."},
  {"lib/jido_code/knowledge/control/reconciliation.ex",
   "The pattern variable __invalid@1 can never match the type, because it is covered by previous clauses."},
  {"lib/jido_code/knowledge/control/transition.ex",
   "Invalid type specification for function statements."},
  {"lib/jido_code/knowledge/decision/follow_up.ex",
   "Invalid type specification for function statements."},
  {"lib/jido_code/knowledge/decision/goal_outcome.ex",
   "The pattern can never match the type true."},
  {"lib/jido_code/knowledge/derivation_request.ex",
   "The pattern variable __invalid@1 can never match the type, because it is covered by previous clauses."},
  {"lib/jido_code/knowledge/evidence/bundle.ex", "The pattern can never match the type true."},
  {"lib/jido_code/knowledge/evidence/claim.ex",
   "Invalid type specification for function statements."},
  {"lib/jido_code/knowledge/execution/event_segment.ex",
   "The pattern variable __invalid@1 can never match the type, because it is covered by previous clauses."},
  {"lib/jido_code/knowledge/execution/interaction_session.ex",
   "The pattern variable __invalid@1 can never match the type, because it is covered by previous clauses."},
  {"lib/jido_code/knowledge/execution/model_invocation.ex",
   "The pattern variable __invalid@1 can never match the type, because it is covered by previous clauses."},
  {"lib/jido_code/knowledge/maintenance.ex",
   "Unknown type: JidoCode.Knowledge.Retention.Receipt.t/0."},
  {"lib/jido_code/knowledge/memory/guardrails.ex", "The pattern can never match the type true."},
  {"lib/jido_code/knowledge/memory/state_transition.ex",
   "Invalid type specification for function statements."},
  {"lib/jido_code/knowledge/query_execution.ex",
   "The pattern pattern {'error', _reason@1} can never match the type, because it is covered by previous clauses."},
  {"lib/jido_code/knowledge/query_execution.ex",
   "The pattern variable __invalid@1 can never match the type, because it is covered by previous clauses."},
  {"lib/jido_code/knowledge/reasoning/service.ex",
   "The pattern can never match the type false | {:ok, atom()}."},
  {"lib/jido_code/knowledge/repositories/enrollment.ex",
   "The pattern variable __invalid@1 can never match the type, because it is covered by previous clauses."},
  {"lib/jido_code/knowledge/repositories/enrollment_transition.ex",
   "Invalid type specification for function statements."},
  {"lib/jido_code/knowledge/resource_identity.ex",
   "The pattern variable __invalid@1 can never match the type, because it is covered by previous clauses."},
  {"lib/jido_code/knowledge/store_server.ex",
   "The pattern pattern {'error', _reason@1} can never match the type, because it is covered by previous clauses."},
  {"lib/jido_code/knowledge/temporal_selection.ex",
   "The pattern variable __invalid@1 can never match the type, because it is covered by previous clauses."},
  {"lib/jido_code/runtime/jido_adapter.ex",
   "The pattern variable __error@1 can never match the type, because it is covered by previous clauses."},
  {"lib/jido_code/runtime/jido_harness/developer_local_launch.ex",
   "Attempt to test for equality with an opaque type %MapSet{:map => MapSet.internal(_)}."},
  {"lib/jido_code/runtime/jido_harness/process_runner.ex",
   "The pattern pattern {'error', _reason@1} can never match the type, because it is covered by previous clauses."},
  {"lib/jido_code/runtime/jido_harness/process_runner.ex",
   "The pattern variable __invalid@1 can never match the type, because it is covered by previous clauses."},
  {"lib/jido_code/runtime/jido_harness/readiness.ex",
   "The pattern pattern <__profile@1, __status@1> can never match the type, because it is covered by previous clauses."},
  {"lib/jido_code/runtime/jido_harness_adapter.ex",
   "The pattern pattern <__request@1, __record@1, __receipt@1, __options@1> can never match the type, because it is covered by previous clauses."},
  {"lib/jido_code/security/redactor.ex", "Unknown type: JidoCode.Security.RedactionReceipt.t/0."},
  {"lib/jido_code_web/frontend_assets.ex", "Unknown type: PhoenixVite.Manifest.t/0."},
  {"lib/mix/tasks/jido_code.ontology.ex", "Function fail/1 has no local return."}
]
