defmodule JidoCode.Knowledge.Evidence.Claim do
  @moduledoc "A precise proposed proposition generated by a verification activity."

  alias JidoCode.Knowledge.Error
  alias JidoCode.Knowledge.GraphRegistry
  alias JidoCode.Knowledge.ResourceIdentity

  @enforce_keys [
    :iri,
    :subject_iri,
    :predicate_iri,
    :object,
    :source_activity_iri,
    :graph_scope_iri,
    :valid_from,
    :valid_to,
    :recorded_at
  ]
  defstruct @enforce_keys

  @type t :: %__MODULE__{}

  @rdf_type "http://www.w3.org/1999/02/22-rdf-syntax-ns#type"
  @rdf_subject "http://www.w3.org/1999/02/22-rdf-syntax-ns#subject"
  @rdf_predicate "http://www.w3.org/1999/02/22-rdf-syntax-ns#predicate"
  @rdf_object "http://www.w3.org/1999/02/22-rdf-syntax-ns#object"
  @jf "https://jido.run/ontology/factory#"
  @prov "http://www.w3.org/ns/prov#"
  @concept "https://jido.run/ontology/concept/"

  @spec new(String.t(), String.t(), map()) :: {:ok, t()} | {:error, Error.t()}
  def new(activity_iri, evidence_graph_iri, attributes) when is_map(attributes) do
    with :ok <- ResourceIdentity.validate(activity_iri),
         {:ok, :evidence} <- GraphRegistry.identify(evidence_graph_iri),
         :ok <- ResourceIdentity.validate(attributes[:subject_iri]),
         true <- predicate?(attributes[:predicate_iri]),
         {:ok, object} <- object(attributes[:object]),
         {:ok, valid_from, valid_to} <- interval(attributes[:valid_from], attributes[:valid_to]),
         recorded_at when is_struct(recorded_at, DateTime) <- attributes[:recorded_at],
         {:ok, iri} <- identity(activity_iri, attributes, object) do
      {:ok,
       %__MODULE__{
         iri: iri,
         subject_iri: attributes[:subject_iri],
         predicate_iri: attributes[:predicate_iri],
         object: object,
         source_activity_iri: activity_iri,
         graph_scope_iri: evidence_graph_iri,
         valid_from: valid_from,
         valid_to: valid_to,
         recorded_at: recorded_at
       }}
    else
      {:error, %Error{} = error} -> {:error, error}
      _invalid -> invalid(:evidence_claim)
    end
  rescue
    _error -> invalid(:evidence_claim)
  end

  def new(_activity_iri, _evidence_graph_iri, _attributes), do: invalid(:evidence_claim)

  @spec statements(t()) :: [RDF.Triple.t()]
  def statements(%__MODULE__{} = claim) do
    [
      {claim.iri, @rdf_type, RDF.iri(@jf <> "Claim")},
      {claim.iri, @rdf_subject, RDF.iri(claim.subject_iri)},
      {claim.iri, @rdf_predicate, RDF.iri(claim.predicate_iri)},
      {claim.iri, @rdf_object, claim.object},
      {claim.iri, @jf <> "sourceActivity", RDF.iri(claim.source_activity_iri)},
      {claim.iri, @jf <> "graphScope", RDF.iri(claim.graph_scope_iri)},
      {claim.iri, @jf <> "epistemicState", RDF.iri(@concept <> "ClaimProposed")},
      {claim.iri, @jf <> "validFrom", RDF.XSD.DateTime.new(claim.valid_from)},
      {claim.iri, @jf <> "validTo", RDF.XSD.DateTime.new(claim.valid_to)},
      {claim.iri, @jf <> "recordedAt", RDF.XSD.DateTime.new(claim.recorded_at)},
      {claim.iri, @prov <> "wasGeneratedBy", RDF.iri(claim.source_activity_iri)}
    ]
  end

  defp object(%{type: :iri, value: value}) when is_binary(value) do
    if safe_iri?(value), do: {:ok, RDF.iri(value)}, else: :error
  end

  defp object(%{type: :string, value: value}) when is_binary(value) do
    if safe_text?(value), do: {:ok, RDF.XSD.String.new(value)}, else: :error
  end

  defp object(%{type: :boolean, value: value}) when is_boolean(value),
    do: {:ok, RDF.XSD.Boolean.new(value)}

  defp object(%{type: :integer, value: value}) when is_integer(value),
    do: {:ok, RDF.literal(value)}

  defp object(_object), do: :error

  defp identity(activity_iri, attributes, object) do
    statement =
      {RDF.iri(attributes.subject_iri), RDF.iri(attributes.predicate_iri), object}
      |> RDF.Triple.new()
      |> List.wrap()
      |> RDF.Graph.new()
      |> RDF.NTriples.write_string!(sort: true)

    ResourceIdentity.deterministic(:evidence_claim, activity_iri <> "\n" <> statement)
  end

  defp interval(%DateTime{} = valid_from, %DateTime{} = valid_to) do
    if DateTime.compare(valid_from, valid_to) == :lt,
      do: {:ok, valid_from, valid_to},
      else: :error
  end

  defp interval(_valid_from, _valid_to), do: :error

  defp predicate?(value) when is_binary(value) do
    String.starts_with?(value, "https://jido.run/ontology/") and safe_iri?(value)
  end

  defp predicate?(_value), do: false

  defp safe_iri?(value),
    do: byte_size(value) <= 512 and RDF.IRI.valid?(value) and not control_character?(value)

  defp safe_text?(value) do
    byte_size(value) in 1..2_048 and not control_character?(value) and
      not Regex.match?(
        ~r/(?:-----BEGIN [A-Z ]*PRIVATE KEY-----|\b(?:gh[pousr]_[A-Za-z0-9]{20,}|sk-[A-Za-z0-9_-]{20,})\b|(?:password|token|secret)\s*[=:]\s*\S+)/i,
        value
      )
  end

  defp control_character?(value), do: Regex.match?(~r/[\x00-\x1F\x7F]/u, value)
  defp invalid(operation), do: {:error, Error.new(:invalid_input, operation)}
end
