import Config

dev_host = System.get_env("PHX_HOST") || "localhost"
dev_port = String.to_integer(System.get_env("PORT") || "4000")
vite_public_host = System.get_env("VITE_PUBLIC_HOST") || dev_host
vite_port = String.to_integer(System.get_env("VITE_PORT") || "5173")

config :live_vue,
  vite_host: "http://#{vite_public_host}:#{vite_port}",
  ssr_module: LiveVue.SSR.ViteJS,
  ssr: true

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :jido_code, JidoCodeWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: dev_port],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "3z97jMiLVa10J18+Y0Bv9BrFEeTh1cImYhIi6vQcprMSwUduHW74LgClkueVGDY8",
  watchers: [vite: {PhoenixVite.Npm, :run, [:vite, ~w(dev)]}],
  static_url: [host: vite_public_host, port: vite_port]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :jido_code, JidoCodeWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
      ~r"priv/gettext/.*(po)$",
      ~r"lib/jido_code_web/(?:controllers|live|components|router)/?.*\.(ex|heex)$"
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :jido_code, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true
