defmodule JidoCode.Repo.Migrations.MigrateResources1 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:github_repos) do
      modify :webhook_secret, :text, default: "__managed_by_secret_ref__"
    end
  end

  def down do
    alter table(:github_repos) do
      modify :webhook_secret, :text, default: nil
    end
  end
end
