defmodule JidoCode.Repo.Migrations.AddSystemConfigs do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:system_configs, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :key, :text, null: false, default: "singleton"
      add :onboarding_completed, :boolean, null: false, default: false
      add :onboarding_step, :bigint, null: false, default: 1
      add :onboarding_state, :map, null: false, default: %{}
      add :default_environment, :text, null: false, default: "sprite"
      add :workspace_root, :text

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:system_configs, [:key], name: "system_configs_unique_key_index")
  end

  def down do
    drop_if_exists unique_index(:system_configs, [:key], name: "system_configs_unique_key_index")

    drop table(:system_configs)
  end
end
